version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  mysql-user:
    image: mysql:8
    environment:
      MYSQL_DB: bigil
      MYSQL_USER: root
      MYSQL_PASSWORD: 142169
    ports:
      - "3306:3306"

  mysql-journal:
    image: mysql:8
    environment:
      MYSQL_DB: bigil
      MYSQL_USER: root
      MYSQL_PASSWORD: 142169
    ports:
      - "5433:5432"

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mysql-user

  journal-service:
    build: ./journal-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mysql-journal
